[phases.setup]
aptPkgs = ["...", "supervisor"]

[phases.build]
cmds = ["...", "chmod +x ./supervisorsetup.sh", "./supervisorsetup.sh"]

[phases.worker]
cmds = ["pwd", "supervisord -c /etc/supervisor/supervisord.conf", "sleep 5", "ps aux | grep supervisord", "sleep 5", "ps aux | grep artisan", "cat /app/worker.log"]
dependsOn = ["build"]

