[phases.setup]
aptPkgs = ["...", "supervisor"]

[phases.build]
cmds = ["...", "chmod +x ./supervisorsetup.sh", "./supervisorsetup.sh"]

[phases.worker]
cmds = ["supervisord -c /etc/supervisor/supervisord.conf", "sleep 5", "supervisorctl status | awk '{print $1, $2}'"]
dependsOn = ["build"]

