[phases.setup]
aptPkgs = ["...", "supervisor"]

[phases.build]
cmds = ["...", "chmod +x ./supervisorsetup.sh", "./supervisorsetup.sh"]

[phases.worker]
cmds = ["supervisord -c /etc/supervisor/supervisord.conf"]
dependsOn = ["build"]

