[phases.setup]
aptPkgs = ["...", "supervisor"]

[phases.build]
cmds = ["...", "chmod +x ./supervisorsetup.sh", "./supervisorsetup.sh"]

[phases.worker]
cmds = ["pwd", "supervisord -c /etc/supervisor/config.d/laravel-worker.conf", "sleep 5", "ps aux | grep supervisord", "sleep 5", "ps aux | grep artisan", "ls /app"]
dependsOn = ["build"]

